class fRekeningKasKecil:
  def __init__(self, formObj, parentForm, mode):
    self.app = formObj.ClientApplication
    self.ObjectAccess = self.app.GetClientClass("ClientObjectAccess", "ObjectAccess")()
    self.mode = mode
    self.ParamDisplay = {
    'New':'self.DisplayNew()',
    'Edit':'self.DisplayEdit()',
    'View':'self.DisplayView()',
    'SENTINEL':''
    }
  def ClearData(self) :
    rec = self.uipData
    rec.Edit()
    stat = rec.Status
    mode = rec.mode
    ID = rec.ID
    user = rec.UserName
    Tgl = rec.OpeningDate
    rec.ClearData()
    rec.Status = stat
    rec.mode = mode
    rec.OpeningDate = Tgl
    rec.UserName = user
    rec.ID = ID
    
  def DisplayNew(self) :
    self.uipData.Edit()
    self.uipData.Status = 'A'
    self.uipData.Balance = 0.0
    self.uipData.AccountNoID = '<AUTOGENERATED>'

  def DisplayEdit(self) :
    self.FormObject.GetPanelByName('pData').GetControlByName(self.uipData.ID+'ID').ReadOnly = 1

  def DisplayView(self) :
    self.FormObject.SetAllControlsReadOnly()
    self.pAction_bOK.Enabled = 1
    self.pAction_bClose.Visible = 0
    self.pAction_bOK.Caption = '&Close'
    self.pAction_bOK.Cancel = 1

  def BranchAfterLookup(self,sender,linkUI):
    uipData = self.uipData
    uipData.Edit()
    uipData.BranchCode = uipData.GetFieldValue("LBranch.Kode_Cabang")

  def CurrencyAfterLookup(self,sender,linkUI):
    uipData = self.uipData
    uipData.Edit()
    uipData.CurrencyCode = uipData.GetFieldValue("LCurrency.Currency_Code")
    
  def UserAfterLookup(self,sender,linkUI):
    uipData = self.uipData
    uipData.Edit()
    uipData.UserName = uipData.GetFieldValue("LUser.Id_User")
    uipData.AccountName = ('Kas Kecil ' + uipData.GetFieldValue("LUser.Nama_User")) [:50]
    
  def FormShow(self, mode) :
    eval(self.ParamDisplay[mode])
    self.FormContainer.Show()
    
  def bOKClick(self, sender):
    if self.pAction_bClose.Visible :
      self.FormObject.CommitBuffer()
      #self.FormObject.PostResult()
      ph = self.FormObject.CallServerMethod('SimpanData',self.FormObject.GetDataPacket())
      status = ph.FirstRecord
      if status.Is_Err == 1 : raise 'ERROR', status.Err_Message
      
    if self.mode == 'New' :
       self.ObjectAccess.ClearuipartData(self.uipData,('Status','mode','ID','UserName','OpeningDate'))
    else :
      sender.ExitAction = 1

