import com.ihsan.foundation.pobjecthelper as phelper
import sys
import simplejson


def FormSetDataEx(uideflist, params) :
  config = uideflist.config
  helper = phelper.PObjectHelper(config)
  Now = config.Now()
  
  if params.GetDatasetByName('trparam') != None :
    oForm = helper.CreateObject('FormTransaksi')
    st = oForm.SetDataEx(uideflist,params)

    rec = uideflist.uipTransaction.Dataset.GetRecord(0)
    
    oTran = helper.GetObjectByNames('Transaction',{'TransactionNo' : rec.TransactionNo})
    
    rec.ActualDate = oTran.GetAsTDateTime('ActualDate')
    
    # Search Object Investment
    TransactionId = params.FirstRecord.TransactionId
    oqlCheck = "select from AccountTransactionItem \
                 [ TransactionId=:TransactionId and \
                   LFinancialAccount.FinancialAccountType='R' ] \
                 (LFinancialAccount.AccountNo, self); "

    oql = config.OQLEngine.CreateOQL(oqlCheck)
    oql.SetParameterValueByName('TransactionId', TransactionId)
    oql.ApplyParamValues()
    oql.active = 1
    recTrans  = oql.rawresult

    if not recTrans.Eof:
      rec.InvestmentAccountNo = recTrans.AccountNo

    # Get Period Id
    tahun = int(config.FormatDateTime('yyyy',Now))
    oBudgetPeriod = helper.GetObjectByNames('BudgetPeriod', {'PeriodValue': tahun})
    rec.PeriodId = oBudgetPeriod.PeriodId
    
    return st

  Now = int(Now)
  rec = uideflist.uipTransaction.Dataset.AddRecord()
  rec.Inputer = str(config.SecurityContext.UserId)
  rec.BranchCode = str(config.SecurityContext.GetUserInfo()[4])
  rec.TransactionDate = Now
  rec.ActualDate = Now
  rec.FloatTransactionDate = Now
  rec.Amount = 0.0
  rec.ReceivedFrom = rec.Inputer
  
  # Set Transaction Number
  oService = helper.LoadScript('Transaction.TransactionHelper')
  rec.TransactionNo = '<AUTOGENERATED>' #oService.GetTransactionNumber(config,'CA')
  
  # Get Period Id
  tahun = int(config.FormatDateTime('yyyy',Now))
  oBudgetPeriod = helper.GetObjectByNames('BudgetPeriod', {'PeriodValue': tahun})
  rec.PeriodId = oBudgetPeriod.PeriodId


def SimpanData(config, params, returns):
  IsErr = 0
  ErrMessage = ''
  TransactionNo = ''
  StreamName = ''
  
  helper = phelper.PObjectHelper(config)
  try :
    oTransaction = params.uipTransaction.GetRecord(0)

    request = {}
    #request['BatchId'] = oTransaction.GetFieldByName('LBatch.BatchId')
    request['ActualDate'] = oTransaction.ActualDate
    request['InvesteeId'] = oTransaction.InvesteeId #oTransaction.GetFieldByName('LEmployee.Nomor_Karyawan')
    request['InvesteeName'] = oTransaction.InvesteeName
    request['InvesteeCategory'] = oTransaction.InvesteeCategory
    request['LifeTime'] = oTransaction.LifeTime
    request['InvestmentCatId'] = oTransaction.GetFieldByName('LInvestmentCategory.InvestmentCatId')
    request['StartDate'] = oTransaction.StartDate
    request['Nisbah'] = oTransaction.Nisbah
    request['InvestmentAccountNo'] = oTransaction.InvestmentAccountNo or ''
    
    request['CashAccountNo'] = oTransaction.GetFieldByName('LCashAccount.AccountNo')
    request['Amount'] = oTransaction.Amount
    request['ReferenceNo'] = oTransaction.ReferenceNo
    request['Description'] = oTransaction.Description
    request['Rate'] = 1.0
    request['Inputer'] = config.SecurityContext.InitUser
    request['BranchCode'] = config.SecurityContext.GetUserInfo()[4]
    request['TransactionNo'] = oTransaction.TransactionNo
    request['ReceivedFrom'] = oTransaction.ReceivedFrom
    request['BudgetCode'] = oTransaction.BudgetCode or ''
    request['BudgetId'] = oTransaction.BudgetId or 0
    request['FundEntity'] = oTransaction.FundEntity or 4
    
    sRequest = simplejson.dumps(request)

    oService = helper.LoadScript('Transaction.GeneralTransaction')
    
    TransactionCode = 'INVS'
    if oTransaction.ShowMode == 1:
      response = oService.CreateTransaction(TransactionCode, config, sRequest, params)
    else:
      response = oService.UpdateTransaction(TransactionCode, config, sRequest, params)
    # end if

    response = simplejson.loads(response)
    TransactionNo = response[u'TransactionNo']

    filename = response[u'FileKwitansi']

    sw = returns.AddStreamWrapper()
    sw.Name = 'Kwitansi'
    sw.LoadFromFile(filename)
    #sw.MIMEType = config.AppObject.GetMIMETypeFromExtension(filename)
    sw.MIMEType = 'application/msword'
    
    StreamName = sw.Name

    IsErr = response[u'Status']
    ErrMessage = response[u'ErrMessage']
    
  except :
    IsErr = 1
    ErrMessage = str(sys.exc_info()[1])

  returns.CreateValues(
     ['IsErr', IsErr],
     ['ErrMessage', ErrMessage],
     ['TransactionNo',TransactionNo],
     ['StreamName',StreamName],
     )

