import com.ihsan.foundation.pobjecthelper as phelper
import sys
import simplejson


def FormSetDataEx(uideflist,params):
  config = uideflist.config

  rec = uideflist.uipBatch.Dataset.AddRecord()
  rec.Inputer = config.SecurityContext.InitUser
  Now = config.Now()
  rec.BatchDate = int(Now)
  rec.Description = '<AUTOGENERATED>'
  rec.BatchNo = '<AUTOGENERATED>'


def CreateBatch(config, params, returns):
  helper = phelper.PObjectHelper(config)
  try :
    oData = params.FirstRecord

    request = {}
    request['Inputer'] = config.SecurityContext.InitUser
    request['BranchCode'] = config.SecurityContext.GetUserInfo()[4]
    request['Description'] = oData.Description
    request['BatchDate'] = oData.BatchDate

    sRequest = simplejson.dumps(request)
    oService = helper.LoadScript('Transaction.Batch')
    sResponse = oService.Create(config, sRequest)
    
    response = simplejson.loads(sResponse)
    returns.CreateValues(['IsErr', 0], ['BatchNo', response[u'BatchNo']],['Description',response[u'Description']])
  except :
    returns.CreateValues(['IsErr', 1], ['ErrMessage', str(sys.exc_info()[1])])

